#!/bin/sh

#set -o errexit
#set -o pipefail
#set -o nounset 

cd "../configurations"
for configuration in *
do
	(

	docker build -t "$DOCKER_REPO:${configuration}" "$configuration/."
	docker push "$DOCKER_REPO:${configuration}"
	#maybe more modpacks/version = to much size used
	docker rmi "$DOCKER_REPO:${configuration}"

	)
done
